### ISSUE TITLE
responsive-bootstrap-toolkit class

### ISSUE THREAD

**Issue by jmarceli** [maciej-gurban/responsive-bootstrap-toolkit#19]
It might be my mistake, but in order to get it to work I **had to** add element with **responsive-bootstrap-toolkit** class. If it is required I would consider updating the documentation/readme.

I installed the it with `bower install responsive-toolkit` (is it official version?, maybe it is outdated?)

**Comment by maciej-gurban** [comment]
Hi jmarceli,

This element should have been added to DOM by the library. Since it wasn't, I'd assume that you included the responsive bootstrap toolkit in <head> section. Is that the case?

If it is so, you could try putting script initialization (the IIFE from examples) inside document.ready() clause. I'm aiming not to have to do any manual labor to make it work, so I'll mark this as a bug, and will resolve it in the nearest release. Thanks for reporting this.

The version you installed is correct. Bower registry should always fetch you the latest version.

**Comment by jmarceli** [comment]
Yes. I've included it inside `<head>` (I didn't find any reason not to do so). Maybe it's not a bug but should be mentioned in the docs to avoid unnecessary confusion.

**Comment by rriopel432** [comment]
I've found that you need to include the script at the end of the body.  If you include it in the head, it tries to create it's div before the body is ready.

**Comment by joelcuevas** [comment]
@maciej-gurban maybe #29 also closes this?

**Comment by maciej-gurban** [comment]
That's correct. I'll mark it as fixed when it's merged into master and a new release is made.

**Comment by maciej-gurban** [comment]
Fixed in 2.5.1, ref: 4732896
