### ISSUE TITLE
viewport.change fires even when viewport has not changed

### ISSUE THREAD

**Issue by bussemac** [maciej-gurban/responsive-bootstrap-toolkit#26]
I was debugging an off-canvas nav on mobile devices, and ultimately tracked the problem to code that looks something like this:
```javascript
$(window).resize(
    viewport.change(function() {
        //close off-canvas nav and reset to default
    });
);
```
When the off-canvas nav "appears", window.resize fires (which is unexpected but at least understandable; we did push something over the edge of the window boundary), but since viewport has not changed (e.g., viewport.current() still reports 'xs') I would not have expected this event to fire. 

Maybe this is working as intended, but it's not clear from the documentation. It's easy to workaround, e.g.
```javascript
$(document).ready(
var __initialviewport = viewport.current();
$(window).resize(function() {
      if (__initialviewport !== viewport.current()) {
        //close off-canvas nav and reset to default
      }
   });
});
```
So again, I don't know if this really is a bug or just needs better documentation.

**Comment by artvorlov** [comment]
Function changed is warper of setTimeout, look at code:
`changed: function(fn, ms) {
            var timer;
            return function(){
                clearTimeout(timer);
                timer = setTimeout(function(){
                    fn();
                }, ms || self.interval);
            };
        }
`
:-)

**Comment by maciej-gurban** [comment]
@bussemac I think I see how that could have been confusing. You've interpreted `viewport.changed` as meaning _breakpoint changed_, due to the fact that `viewport.current()` returns current breakpoint alias, not viewport size (or any of viewports' dimensions). However, _changed_ method merely serves (as @artvorlov mentioned), as a wrapper around code you want executed on window.resize (= viewport resize). 

I'm afraid I cannot supplement `changed` method with a conditional statement you used, since it's impossible to know how other developers are using said method. Some might use it just for debouncing window resize events, in which case all such checks would cease to work. What I could do however, is to create either
- a new method (`differs`?) returning true/false whenever breakpoint actually differs, or doesn't
- a new method, (`previous`?) that would contain alias of previous breakpoint

I'm open for suggestions which way would be more natural to solve this.

**Comment by bussemac** [comment]
Hmm, doesn't seem that useful, but I guess if you want to respond to any
screen resize, as opposed to a breakpoint change (which makes more sense
since bootstrap isn't going to change your layout unless the breakpoint
changed). Maybe I'll write up breakpointchanged and send a pull request.

**Comment by maciej-gurban** [comment]
I thought about it a little, and I agree with your logic. Due to reasons already mentioned, I cannot apply this change currently, however, I do plan on introducing this change in the next major release. There'll be a ticket with proposed v3 changes soon.
