### ISSUE TITLE
Inclusion inside head not working

### ISSUE THREAD

**Issue by joelcuevas** [maciej-gurban/responsive-bootstrap-toolkit#28]
I see that you made a fix in 2.4.2 to try to solve this.

Nevertheless, although you delayed the inclusion of visibility divs until the body is completely loaded, you didn't consider the container of those divs and, at least for me, this feature is still not working.

The solution is simple: just delay that append. 

I'll be submiting a PR as soon as I finish writing this. Hope you can check it out.

**Comment by maciej-gurban** [comment]
Hi Joel!

Thank you for your PR. Your fix made me realize an important aspect I left out of the documentation, and which should absolutely be there. No RT method should be called before `document.ready()`. Otherwise, wrong results will be reported. 

I was attempting to do something about it, but perhaps it's an unnecessary (or at least too ambitious) undertaking.

Thanks!

**Comment by joelcuevas** [comment]
What do you mean with "RT"? I'm not familiar with the term. :stuck_out_tongue:

**Comment by maciej-gurban** [comment]
Oh yes, I made sharp shortcut ;) Responsive Bootstrap Toolkit -> Responsive Toolkit -> RT ;)

**Comment by maciej-gurban** [comment]
Fixed in 2.5.1, ref: 4732896
